---
title: "Graph"
date: "`r Sys.Date()`"
output:
  html_document:
    df_print: paged
    toc: true
---
```{r setup, include = FALSE}
suppressWarnings(source("./fct/sources.R"))
# knitr::opts_chunk$set(cache = TRUE)

require(devtools)
library(knitr)
library(rmarkdown)
library(wordcloud2)
library(dplyr)
```


```{r analyse, eval=FALSE, include=FALSE}
## analyse de mot
CopyS <- data.frame(aListes())

main <- function(){
  max <- 30
  CopyS <- na.omit(CopyS)
  
  ec <- CopyS %>% filter(nbMotEc >= 1)
  ec2 <- ec %>% arrange(desc(ec$nbMotEc))
  barplot(ec$nbMotEc, 
          las = 2, 
          names.arg = ec$motEc,
          col =brewer.pal(8, "Dark2"), 
          main ="Top mot Ec",
          ylab = "Word frequencies",
          ylim=c(0,100),
          xlim=c(0,96)
          )
  box()
  #pie(ec2$nbMotEc,label=paste(ec2$motEc,"",ec2$nbMotEc))
  
  
  
  
  
  
}
suppressWarnings(main())
```

## en cours
```{r ecocc, echo=FALSE}
CopyS <- data.frame(aECocc())
CopyS <- data.frame(CopyS[1:6])
main <- function(){
  max <- 30
# CopyS <- data.frame()
  CopyS <- na.omit(CopyS)
  print("semaine")
  sem <- CopyS %>% filter(occ.ECS >= 1)
  sem2 <- sem %>% arrange(desc(sem$occ.ECS))
  barplot(sem$occ.ECS, 
          las = 2, 
          names.arg = sem$en.cours,
          col =brewer.pal(8, "Dark2"), 
          main ="Top semaine",
          ylab = "Word frequencies",
          ylim=c(0,max(sem$occ.ECS)*1.1))
  box()
  pie(sem2$occ.ECS,label=paste(sem2$en.cours,"",sem2$occ.ECS))
  print("mois")
  mois <- CopyS %>% filter(occ.ECM >= 1)
  mois2 <- mois %>% arrange(desc(mois$occ.ECM))
  barplot(mois$occ.ECM, 
          las = 2, 
          names.arg = mois$en.cours,
          col =brewer.pal(8, "Dark2"), 
          main ="Top mois",
          ylab = "Word frequencies",
          ylim=c(0,max(mois$occ.ECM)*1.1))
  box()
  pie(mois2$occ.ECM,label=paste(mois2$en.cours,"",mois2$occ.ECM))
  print("recent")
  rec <- CopyS %>% filter(occ.ECR >= 1)
  rec2 <- rec %>% arrange(desc(rec$occ.ECR))
  barplot(rec$occ.ECR, 
          las = 2, 
          names.arg = rec$en.cours,
          col =brewer.pal(8, "Dark2"), 
          main ="Top recent",
          ylab = "Word frequencies",
          ylim=c(0,max(rec$occ.ECR)*1.1))
  box()
  pie(rec2$occ.ECR,label=paste(rec2$en.cours,"",rec2$occ.ECR))
  print("tout")
  barplot(CopyS$count, 
          las = 2, 
          names.arg = CopyS$tisa.en.cours,
          col =brewer.pal(8, "Dark2"), 
          main ="Top all",
          ylab = "Word frequencies",
          ylim=c(0,max(CopyS$count)*1.1))
  box()
  print("---")
  barplot(t(as.matrix(CopyS[2:4])), 
          las = 2, 
          names.arg = CopyS$en.cours,
          col =c("red","blue","green"), 
          main ="Top ---",
          ylab = "Word frequencies",
          beside = TRUE,
          ylim=c(0,max(CopyS$occ.ECR)*1.1))
  box()
  legend('topright',fill=c("red","blue","green"),legend=c('recent','mois','sem'))
}
suppressWarnings(main())
```

## termine
```{r terocc, echo=FALSE}
CopyS <- data.frame(aECocc())
CopyS <- data.frame(CopyS[7:12])
main <- function(){
  max <- 30
# CopyS <- data.frame()
  CopyS <- na.omit(CopyS)
  print("semaine")
  sem <- CopyS %>% filter(occ.FINIS >= 1)
  barplot(sem$occ.FINIS, 
          las = 2, 
          names.arg = sem$fini,
          col =brewer.pal(8, "Dark2"), 
          main ="Top semaine",
          ylab = "Word frequencies",
          ylim=c(0,max(sem$occ.FINIS)*1.1))
  box()
  print("mois")
  mois <- CopyS %>% filter(occ.FINIM >= 1)
  barplot(mois$occ.FINIM, 
          las = 2, 
          names.arg = mois$fini,
          col =brewer.pal(8, "Dark2"), 
          main ="Top mois",
          ylab = "Word frequencies",
          ylim=c(0,max(mois$occ.FINIM)*1.1))
  box()
  print("recent")
  barplot(CopyS$occ.FINIR, 
          las = 2, 
          names.arg = CopyS$fini,
          col =brewer.pal(8, "Dark2"), 
          main ="Top recent",
          ylab = "Word frequencies",
          ylim=c(0,max(CopyS$occ.FINIR)*1.1))
  box()
  print("tout")
  barplot(CopyS$count_1, 
          las = 2, 
          names.arg = CopyS$tisa.terminée,
          col =brewer.pal(8, "Dark2"), 
          main ="Top all",
          ylab = "Word frequencies",
          ylim=c(0,max(CopyS$count_1)*1.1))
  box()
  print("---")
  barplot(t(as.matrix(CopyS[2:4])), 
          las = 2, 
          names.arg = CopyS$fini,
          col =c("red","blue","green"), 
          main ="Top ---",
          ylab = "Word frequencies",
          beside = TRUE,
          ylim=c(0,max(CopyS$occ.FINIR)*1.1))
  box()
  legend('topright',fill=c("red","blue","green"),legend=c('recent','mois','sem'))
}
suppressWarnings(main())
```

## temps
```{r temps, echo=FALSE}

df <- data.frame(accueil())
layout(matrix(1:4,2,2))

# print("heures")
barplot(table(df$hh),
        las = 2,
        col =brewer.pal(8, "Dark2"), 
        main ="ep per hours",
        ylab = "nb ep",
        ylim=c(0,max(table(df$hh))*1.1)
        )
box()
# print("minutes")
barplot(table(df$minute),
        las = 2,
        col =brewer.pal(8, "Dark2"), 
        main ="ep per minutes",
        ylab = "nb ep",
        ylim=c(0,max(table(df$minute))*1.1)
        )
box()

# print("secondes")
barplot(table(df$sec),
        las = 2,
        col =brewer.pal(8, "Dark2"), 
        main ="ep per seconds",
        ylab = "nb ep",
        ylim=c(0,max(table(df$sec))*1.1)
        )
box()
```

## accueil
```{r acc, echo=FALSE}

df <- data.frame(accueil())
layout(matrix(1:4,2,2))
# print("saison")
barplot(table(df$saison),
        las = 2,
        col =brewer.pal(8, "Dark2"), 
        main ="saison",
        ylab = "nb ep",
        ylim=c(0,max(table(df$saison))*1.1)
        )
box()
# print("episode")
barplot(table(df$episode),
        las = 2,
        col =brewer.pal(8, "Dark2"), 
        main ="episode",
        ylab = "nb ep",
        ylim=c(0,max(table(df$episode))*1.1)
        )
box()
# print("status")
barplot(table(df$status),
        las = 2,
        col =brewer.pal(8, "Dark2"), 
        main ="status",
        ylab = "nb ep",
        ylim=c(0,max(table(df$status))*1.1)
        )
box()
# print("indice")
barplot(table(df$indice),
        las = 2,
        col =brewer.pal(8, "Dark2"), 
        main ="indice",
        ylab = "nb ep",
        ylim=c(0,max(table(df$indice))*1.1)
        )
box()

```

## copy
```{r copy, echo=FALSE}

df <- data.frame(aCopyScript())
layout(matrix(1:4,2,2))

# print("nb titre sem")
barplot(table(df$nrs),
        las = 2,
        col =brewer.pal(8, "Dark2"), 
        main ="nb titre sem",
        ylab = "nb sem with x titles",
        ylim=c(0,max(table(df$nrs))*1.1)
        )
box()
# print("nb caractere sem")
barplot(table(df$nbCar),
        las = 2,
        col =brewer.pal(8, "Dark2"), 
        main ="nb caractere sem",
        ylab = "nb sem with x car",
        ylim=c(0,max(table(df$nbCar))*1.1)
        )
box()
# print("nb titre mois")
barplot(table(df$nrm),
        las = 2,
        col =brewer.pal(8, "Dark2"), 
        main ="nb titre mois",
        ylab = "nb mois with x titles",
        ylim=c(0,max(table(df$nrm))*1.1)
        )
box()

# print("nb caractere mois")
barplot(table(df$nbCar_1),
        las = 2,
        col =brewer.pal(8, "Dark2"), 
        main ="nb caractere mois",
        ylab = "nb mois with x car",
        ylim=c(0,max(table(df$nbCar_1))*1.1)
        )
box()
layout(matrix(1:2,1,2))
# print("nb titre conclu")
barplot(table(df$nc),
        las = 2,
        col =brewer.pal(8, "Dark2"), 
        main ="nb titre conclu",
        ylab = "nc",
        ylim=c(0,max(table(df$nc))*1.1)
        )
box()
# print("nb titre conclubis")
barplot(table(df$ncb),
        las = 2,
        col =brewer.pal(8, "Dark2"), 
        main ="nb titre conclubis",
        ylab = "ncb",
        ylim=c(0,max(table(df$ncb))*1.1)
        )
box()
```
