---
title: "Series and co"
date: "`r Sys.Date()`"
output:
  html_document:
    df_print: paged
    toc: true
---
```{r setup, include = FALSE}
suppressWarnings(source("./fct/sources.R"))
# knitr::opts_chunk$set(cache = TRUE)

require(devtools)
library(knitr)
library(rmarkdown)
library(wordcloud2)
```


```{r render, eval=FALSE, include=FALSE}
# rmarkdown::clean_site()
page <- c("index.Rmd","networks.Rmd","listes.Rmd","wordcloud.Rmd")
for (i in 1:4){
knit(page[i])
render(page[i])
}

# rmarkdown::render_site("index.Rmd")
# rmarkdown::render_site("networks.Rmd")
# rmarkdown::render_site("listes.Rmd")
# rmarkdown::render_site("wordcloud.Rmd")
```

## conclu
```{r concluG, echo = FALSE}
CopyS <-data.frame(copy.conclu())
dataC <- data.frame(CopyS$nbCarConclu,CopyS$nbCarConcluBis,CopyS$jour_1,CopyS$date)
  
  plot(CopyS$nbCarConcluBis,main="nb de caracteres conclu",type = "l",col="red",xlab = "date",ylab = "nb car")
  lines(CopyS$nbCarConcluBis,type = "l",col="red")
  lines(CopyS$nbCarConclu,type = "l",col="blue")
  
```

## max
```{r max, echo = FALSE}
CopyS <- data.frame(copy.max())
main <- function(){
# CopyS <- data.frame()
  CopyS <- na.omit(CopyS)
  plot(CopyS$NBog,main="max",type = "l",col="red",xlab = "date",ylab = "nb")
  lines(CopyS$NBog,type = "l",col="red")
  lines(CopyS$NBactuel,type = "l",col="blue")
}
suppressWarnings(main())
```

## en cours
```{r ecocc, echo=FALSE}
CopyS <- data.frame(aECocc())
CopyS <- data.frame(CopyS[1:6])
main <- function(){
  max <- 30
# CopyS <- data.frame()
  CopyS <- na.omit(CopyS)
  print("semaine")
  barplot(CopyS$occ.ECS, 
          las = 2, 
          names.arg = CopyS$en.cours,
          col =brewer.pal(8, "Dark2"), 
          main ="Top semaine",
          ylab = "Word frequencies",
          ylim=c(0,max(CopyS$occ.ECS)*1.1))
  box()
  print("mois")
  barplot(CopyS$occ.ECM, 
          las = 2, 
          names.arg = CopyS$en.cours,
          col =brewer.pal(8, "Dark2"), 
          main ="Top mois",
          ylab = "Word frequencies",
          ylim=c(0,max(CopyS$occ.ECM)*1.1))
  box()
  print("recent")
  barplot(CopyS$occ.ECR, 
          las = 2, 
          names.arg = CopyS$en.cours,
          col =brewer.pal(8, "Dark2"), 
          main ="Top recent",
          ylab = "Word frequencies",
          ylim=c(0,max(CopyS$occ.ECR)*1.1))
  box()
  print("tout")
  barplot(CopyS$count, 
          las = 2, 
          names.arg = CopyS$tisa.en.cours,
          col =brewer.pal(8, "Dark2"), 
          main ="Top all",
          ylab = "Word frequencies",
          ylim=c(0,max(CopyS$count)*1.1))
  box()
  print("---")
  barplot(t(as.matrix(CopyS[2:4])), 
          las = 2, 
          names.arg = CopyS$en.cours,
          col =c("red","blue","green"), 
          main ="Top ---",
          ylab = "Word frequencies",
          beside = TRUE,
          ylim=c(0,max(CopyS$occ.ECR)*1.1))
  box()
  legend('topright',fill=c("red","blue","green"),legend=c('recent','mois','sem'))
}
suppressWarnings(main())
```

## termine
```{r terocc, echo=FALSE}
CopyS <- data.frame(aECocc())
CopyS <- data.frame(CopyS[7:12])
main <- function(){
  max <- 30
# CopyS <- data.frame()
  CopyS <- na.omit(CopyS)
  print("semaine")
  barplot(CopyS$occ.FINIS, 
          las = 2, 
          names.arg = CopyS$fini,
          col =brewer.pal(8, "Dark2"), 
          main ="Top semaine",
          ylab = "Word frequencies",
          ylim=c(0,max(CopyS$occ.FINIS)*1.1))
  box()
  print("mois")
  barplot(CopyS$occ.FINIM, 
          las = 2, 
          names.arg = CopyS$fini,
          col =brewer.pal(8, "Dark2"), 
          main ="Top mois",
          ylab = "Word frequencies",
          ylim=c(0,max(CopyS$occ.FINIM)*1.1))
  box()
  print("recent")
  barplot(CopyS$occ.FINIR, 
          las = 2, 
          names.arg = CopyS$fini,
          col =brewer.pal(8, "Dark2"), 
          main ="Top recent",
          ylab = "Word frequencies",
          ylim=c(0,max(CopyS$occ.FINIR)*1.1))
  box()
  print("tout")
  barplot(CopyS$count_1, 
          las = 2, 
          names.arg = CopyS$tisa.terminée,
          col =brewer.pal(8, "Dark2"), 
          main ="Top all",
          ylab = "Word frequencies",
          ylim=c(0,max(CopyS$count_1)*1.1))
  box()
  print("---")
  barplot(t(as.matrix(CopyS[2:4])), 
          las = 2, 
          names.arg = CopyS$fini,
          col =c("red","blue","green"), 
          main ="Top ---",
          ylab = "Word frequencies",
          beside = TRUE,
          ylim=c(0,max(CopyS$occ.FINIR)*1.1))
  box()
  legend('topright',fill=c("red","blue","green"),legend=c('recent','mois','sem'))
}
suppressWarnings(main())
```

## temps
```{r heure, echo=FALSE}

df <- data.frame(accueil())
print("heures")
barplot(table(df$hh),
        las = 2,
        col =brewer.pal(8, "Dark2"), 
        main ="ep per hours",
        ylab = "nb ep",
        ylim=c(0,max(table(df$hh))*1.1)
        )
box()
print("minutes")
barplot(table(df$minute),
        las = 2,
        col =brewer.pal(8, "Dark2"), 
        main ="ep per minutes",
        ylab = "nb ep",
        ylim=c(0,max(table(df$minute))*1.1)
        )
box()
print("secondes")
barplot(table(df$sec),
        las = 2,
        col =brewer.pal(8, "Dark2"), 
        main ="ep per seconds",
        ylab = "nb ep",
        ylim=c(0,max(table(df$sec))*1.1)
        )
box()
```
