---
title: "listes"
date: "`r Sys.Date()`"
output:
  html_document:
    df_print: paged
    toc: true
---
```{r setup, include = FALSE}
suppressWarnings(source("./fct/sources.R"))
suppressWarnings(library(tidyverse))
# knitr::opts_chunk$set(cache = TRUE)
```

## historique
```{r hist, echo=FALSE}
data <- data.frame(listDesc.desc())
data %>% select(tisaep,Horodateur,status) 
```

## debut
```{r lettre, echo=FALSE}
data <- data.frame(listDesc.desc())
data %>% filter(episode == 1,status=="en cours") %>% select(tisaep,Horodateur,descr.img) 

```

## liste EC : alea
```{r alea, echo=FALSE}

data <- data.frame(listDesc.desc())
max <- 100
data %>% filter(status == "en cours") %>% sample_n(max) %>% group_by(tisa) %>% summarise(pc = n()) %>% arrange(desc(pc)) %>% filter(pc >= 3)
```

## liste EC : Titre
```{r titre, echo=FALSE}
df <- data.frame(listDesc.ec())
data <- data.frame(listDesc.desc())
data <- distinct(data)
# titre = readline()
titre = df[1,2]
data %>% filter(Titre == titre) %>% select(tisaep,Horodateur) 
if(data[2,2] == data[1,2]){
  titre = df[3,2]
} else {
  titre = df[2,2]
}
data %>% filter(Titre == titre) %>% select(tisaep,Horodateur) 
```

## liste EC
```{r ec, echo=FALSE}
data <- data.frame(listDesc.desc())
data %>% filter(status == "en cours") %>% select(tisaep,Horodateur) 
```

## liste TER
```{r ter, echo=FALSE}
data <- data.frame(listDesc.desc())
data %>% filter(status == "terminée") %>% select(tisaep,Horodateur) 
```

## liste film
```{r film, echo=FALSE}
data <- data.frame(listDesc.desc())
data %>% filter(status == "film") %>% select(tisaep,Horodateur) 
```

## premder ec
```{r premDerEc, echo=FALSE}
data <- data.frame(premder.ec())
data %>% filter(tisaep.all_2 != "")  %>% select(tisaep.all_2
,date.premder.all_2) 
```

## premder
```{r premder, echo=FALSE}
data <- data.frame(premder.premder())
data %>% filter(tisaep.all_1 != "") %>% select(tisaep.all_1,date.premder.all_1,status.all_1) 
```

## prem der
```{r premDer, echo=FALSE}
data <- data.frame(premder.prem.der())
data %>% filter(tisaep.all != "")  %>% select(tisaep.all
,date.premder.all,status.all) 
```

## nb
```{r nb, echo=FALSE}
data <- data.frame(aListes())

# df <- data.frame(cbind(data$titre,data$nbDeLignes,data$titre_1,data$nbPage))
# df[1:50,]

data %>% filter(titre != "")  %>% select(titre,nbDeLignes) 
data %>% filter(titre_1 != "")  %>% select(titre_1,nbPage) 
```
